apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-demo-deployment

spec:
  replicas: 4

  selector:
    matchLabels:
      app: devops-demo

  template:
    metadata:
      labels:
        app: devops-demo

    spec:
      containers:
        - name: devops-demo-container
          image: rp001/devops-demo-app:latest

          ports:
            - containerPort: 8080